#!/usr/bin/env python3
"""Run a bounded EnsExam-GAN training probe and save a checkpoint.

This intentionally bypasses the full train.py epoch loop so we can verify a
loss/objective change with fixed compute on MPS.
"""

from __future__ import annotations

import argparse
import csv
import gc
import os
import random
import sys
import time
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config_loader import load_config, save_config  # noqa: E402
from data.dataset import EnsExamRealDataset  # noqa: E402
from losses.losses import EnsExamLoss  # noqa: E402
from networks.discriminator import Discriminator  # noqa: E402
from networks.generator import Generator  # noqa: E402
from train import load_optional_file_list, setup_device  # noqa: E402
from utils.path_utils import normalize_path  # noqa: E402


def parse_scalar(value: str) -> object:
    lowered = value.lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    try:
        if any(ch in value for ch in (".", "e", "E")):
            return float(value)
        return int(value)
    except ValueError:
        return value


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--max-steps", type=int, default=80)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--train-pages", type=int, default=16)
    parser.add_argument(
        "--train-file-list",
        default=None,
        help=(
            "Optional newline-delimited training image list. Overrides "
            "data.train_file_list from the config. Entries may be filenames "
            "or full paths; only basenames are used by EnsExamRealDataset."
        ),
    )
    parser.add_argument(
        "--patch-index-file",
        default=None,
        help=(
            "Optional CSV generated by build_hard_patch_list.py. When set, "
            "training is restricted to matching filename/x1/y1 patches."
        ),
    )
    parser.add_argument("--log-every", type=int, default=10)
    parser.add_argument("--save-every", type=int, default=10)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--disable-augmentation", action="store_true")
    parser.add_argument(
        "--device-override",
        default=None,
        help="Override train.device for local smoke runs, e.g. cpu when MPS is unavailable.",
    )
    parser.add_argument(
        "--box-class-mode",
        choices=("all", "target_diff"),
        default="all",
        help=(
            "Controls box_label_txt classes used for Mb_gt. Default keeps all "
            "classes; target_diff infers erase classes from local input/target differences."
        ),
    )
    parser.add_argument(
        "--box-preserve-mode",
        choices=("none", "target_diff_non_erase"),
        default="none",
        help=(
            "Optional auxiliary preserve-mask source. target_diff_non_erase "
            "preserves box classes not inferred as erase targets."
        ),
    )
    parser.add_argument(
        "--loss-override",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help=(
            "Override one loss config value for bounded probes, e.g. "
            "--loss-override lambda_input_preserve=14.0. May be repeated."
        ),
    )
    parser.add_argument(
        "--trace-batches-file",
        default=None,
        help=(
            "Optional CSV path for recording the actual sampled patch metadata "
            "for each training step. This is useful for one-step probes where "
            "the sampled patch identity dominates the result."
        ),
    )
    parser.add_argument(
        "--mask-only",
        action="store_true",
        help=(
            "Train only mask prediction branches with Ms/Mb supervision. This "
            "skips discriminator and reconstruction losses so explicit-mask "
            "datasets can tune erase eligibility without pushing image synthesis."
        ),
    )
    parser.add_argument(
        "--mask-train-scope",
        choices=("heads", "decoder", "coarse", "all"),
        default="decoder",
        help=(
            "Trainable generator scope used with --mask-only. heads updates only "
            "out_ms/out_mb; decoder updates mask_up/mask_conv/out heads; coarse "
            "updates all coarse-net parameters; all updates the whole generator."
        ),
    )
    parser.add_argument(
        "--mask-bce-weight",
        type=float,
        default=0.25,
        help="Optional BCE term weight for --mask-only. Set 0 to use SN/Dice only.",
    )
    parser.add_argument(
        "--mask-bce-negative-weight",
        type=float,
        default=0.1,
        help="Relative background weight for the --mask-only BCE term.",
    )
    return parser.parse_args()


def sn_loss(Ms: torch.Tensor, Ms_gt: torch.Tensor) -> torch.Tensor:
    """Sparse-normalized L1 mask loss matching EnsExamLoss.sn_loss."""
    sum_gt = torch.sum(Ms_gt, dim=tuple(range(1, Ms.dim())))
    valid_mask = (sum_gt > 1.0).float()
    if valid_mask.sum() == 0:
        return Ms.sum() * 0
    l1_sum = torch.sum(torch.abs(Ms - Ms_gt), dim=tuple(range(1, Ms.dim())))
    sum_pred = torch.sum(Ms, dim=tuple(range(1, Ms.dim())))
    normalization = torch.min(sum_pred, sum_gt)
    loss_batch = l1_sum / (normalization + 1e-6)
    return (loss_batch * valid_mask).sum() / (valid_mask.sum() + 1e-6)


def block_loss(Mb: torch.Tensor, Mb_gt: torch.Tensor) -> torch.Tensor:
    """Dice block-mask loss matching EnsExamLoss.block_loss."""
    inter = (Mb * Mb_gt).sum([1, 2, 3])
    denom = (Mb ** 2).sum([1, 2, 3]) + (Mb_gt ** 2).sum([1, 2, 3])
    return (1 - 2 * inter / (denom + 1e-8)).mean()


def weighted_mask_bce(pred: torch.Tensor, target: torch.Tensor, negative_weight: float) -> torch.Tensor:
    """BCE that keeps positive mask pixels from being diluted by the page background."""
    pred = pred.clamp(1e-6, 1 - 1e-6)
    weights = torch.where(target > 0.5, torch.ones_like(target), torch.full_like(target, negative_weight))
    loss = F.binary_cross_entropy(pred, target, reduction="none") * weights
    denom = weights.sum(dim=(1, 2, 3))
    valid = denom > 1.0
    if valid.sum() == 0:
        return loss.sum() * 0
    per_sample = loss.sum(dim=(1, 2, 3)) / (denom + 1e-6)
    return per_sample[valid].mean()


def set_mask_only_trainable(G: Generator, scope: str) -> int:
    """Freeze generator parameters outside the requested mask-training scope."""
    prefixes_by_scope = {
        "heads": ("coarse.out_ms", "coarse.out_mb"),
        "decoder": (
            "coarse.mask_up_",
            "coarse.mask_conv_",
            "coarse.out_ms",
            "coarse.out_mb",
        ),
        "coarse": ("coarse.",),
        "all": ("",),
    }
    prefixes = prefixes_by_scope[scope]
    trainable = 0
    for name, param in G.named_parameters():
        enabled = any(name.startswith(prefix) for prefix in prefixes)
        param.requires_grad_(enabled)
        if enabled:
            trainable += param.numel()
    return trainable


def main() -> None:
    args = parse_args()
    cfg = load_config(args.config)
    cfg["train"]["batch_size"] = args.batch_size
    cfg["train"]["num_workers"] = 0
    if args.device_override:
        cfg["train"]["device"] = args.device_override
    for raw_override in args.loss_override:
        if "=" not in raw_override:
            raise ValueError(f"loss override must be KEY=VALUE: {raw_override}")
        key, value = raw_override.split("=", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"loss override key is empty: {raw_override}")
        cfg["loss"][key] = parse_scalar(value.strip())
    if args.disable_augmentation:
        cfg["data"]["augmentation"] = None

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    save_config(cfg, str(output_dir / "config.yaml"))

    device, _ = setup_device(cfg["train"])
    print(f"device={device}", flush=True)
    print(f"normalize_lr_regions={cfg['loss'].get('normalize_lr_regions')}", flush=True)
    if args.loss_override:
        print(f"loss_overrides={args.loss_override}", flush=True)
    print(f"seed={args.seed}", flush=True)
    print(f"augmentation_enabled={cfg['data'].get('augmentation') is not None}", flush=True)
    if args.mask_only:
        print(
            "mask_only=true "
            f"scope={args.mask_train_scope} "
            f"bce_weight={args.mask_bce_weight} "
            f"bce_negative_weight={args.mask_bce_negative_weight}",
            flush=True,
        )

    train_file_list = args.train_file_list
    if train_file_list is None:
        train_file_list = cfg["data"].get("train_file_list", "")
    train_files = load_optional_file_list(train_file_list)
    if train_files is not None:
        train_files = train_files[: args.train_pages]
        print(f"train_file_list={train_file_list}", flush=True)
        print(f"train_files_used={len(train_files)}", flush=True)
        print(f"train_files_head={','.join(train_files[:8])}", flush=True)

    dataset = EnsExamRealDataset(
        data_root=cfg["data"]["data_root"],
        img_size=cfg["data"]["img_size"],
        is_train=True,
        overlap=cfg["data"]["overlap"],
        mask_threshold=cfg["data"]["mask_threshold"],
        aug_cfg=cfg["data"].get("augmentation"),
        file_list=train_files,
        phase="train",
        box_class_mode=args.box_class_mode,
        box_preserve_mode=args.box_preserve_mode,
    )
    if args.patch_index_file:
        patch_index_path = Path(args.patch_index_file)
        wanted: set[tuple[str, int, int]] = set()
        with patch_index_path.open("r", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                wanted.add((row["file"], int(row["x1"]), int(row["y1"])))
        before = len(dataset.patch_index_map)
        dataset.patch_index_map = [
            info for info in dataset.patch_index_map
            if (Path(info["img_path"]).name, int(info["x1"]), int(info["y1"])) in wanted
        ]
        print(f"patch_index_file={patch_index_path}", flush=True)
        print(f"patches_filtered={before}->{len(dataset.patch_index_map)}", flush=True)
        if not dataset.patch_index_map:
            raise RuntimeError(f"patch index filter produced no patches: {patch_index_path}")
    class _IndexedDataset(torch.utils.data.Dataset):
        def __init__(self, wrapped):
            self.wrapped = wrapped

        def __len__(self):
            return len(self.wrapped)

        def __getitem__(self, index):
            item = self.wrapped[index]
            return (*item, torch.tensor(index, dtype=torch.long))

    trace_path = Path(args.trace_batches_file) if args.trace_batches_file else None
    loader_dataset = _IndexedDataset(dataset) if trace_path else dataset
    if trace_path:
        trace_path.parent.mkdir(parents=True, exist_ok=True)
        with trace_path.open("w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(["step", "dataset_index", "file", "x1", "y1", "x2", "y2"])

    loader = DataLoader(
        loader_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=0,
        drop_last=True,
        generator=torch.Generator().manual_seed(args.seed),
    )

    G = Generator(cfg=cfg["model"]).to(device)
    D = Discriminator().to(device)
    ckpt_path = normalize_path(cfg["train"]["resume_path"])
    ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
    G.load_state_dict(ckpt["G_state_dict"])
    D.load_state_dict(ckpt["D_state_dict"])

    if args.mask_only:
        trainable_params = set_mask_only_trainable(G, args.mask_train_scope)
        D.requires_grad_(False)
        print(f"mask_only_trainable_params={trainable_params}", flush=True)
        criterion = None
    else:
        trainable_params = sum(p.numel() for p in G.parameters() if p.requires_grad)
        print(f"generator_trainable_params={trainable_params}", flush=True)
        criterion = EnsExamLoss(cfg["loss"]).to(device)
    lr = args.lr if args.lr is not None else cfg["train"]["lr"]
    opt_g = torch.optim.Adam(
        [p for p in G.parameters() if p.requires_grad],
        lr=lr,
        betas=tuple(cfg["train"]["adam_betas"]),
    )
    opt_d = torch.optim.Adam(
        D.parameters(),
        lr=lr,
        betas=tuple(cfg["train"]["adam_betas"]),
    )

    history_path = output_dir / "micro_loss_history.csv"
    with history_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "step",
            "loss_G",
            "loss_D",
            "adv",
            "lr",
            "per",
            "style",
            "sn",
            "block",
            "input_preserve",
            "mb_leak",
            "box_preserve",
            "mask_bce",
        ])

    def save_checkpoint(path: Path, steps_done: int) -> None:
        out_ckpt = {
            "epoch": int(ckpt.get("epoch", 0)),
            "micro_steps": steps_done,
            "G_state_dict": G.state_dict(),
            "D_state_dict": D.state_dict(),
            "optimizer_G": opt_g.state_dict(),
            "optimizer_D": opt_d.state_dict(),
            "source_checkpoint": ckpt_path,
            "config": cfg,
        }
        torch.save(out_ckpt, path)

    start = time.time()
    data_iter = iter(loader)
    G.train()
    D.train(not args.mask_only)

    for step in range(1, args.max_steps + 1):
        try:
            batch = next(data_iter)
        except StopIteration:
            data_iter = iter(loader)
            batch = next(data_iter)

        sampled_indices = None
        if trace_path:
            *batch, sampled_indices = batch
        batch = [t.to(device) for t in batch]
        if trace_path and sampled_indices is not None:
            with trace_path.open("a", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                for sampled_index in sampled_indices.tolist():
                    info = dataset.patch_index_map[int(sampled_index)]
                    writer.writerow([
                        step,
                        int(sampled_index),
                        Path(info["img_path"]).name,
                        int(info["x1"]),
                        int(info["y1"]),
                        int(info["x2"]),
                        int(info["y2"]),
                    ])
        Box_preserve_gt = None
        if len(batch) == 8:
            Iin, Ms_gt, Mb_gt, Box_preserve_gt, Igt4, Igt2, Igt1, Igt = batch
            gt = (Iin, Ms_gt, Mb_gt, Box_preserve_gt, Igt4, Igt2, Igt1, Igt)
        else:
            Iin, Ms_gt, Mb_gt, Igt4, Igt2, Igt1, Igt = batch
            gt = (Iin, Ms_gt, Mb_gt, Igt4, Igt2, Igt1, Igt)

        opt_g.zero_grad(set_to_none=True)
        if args.mask_only:
            Ms, Mb, *_ = G(Iin)
            L_sn = sn_loss(Ms, Ms_gt) * float(cfg["loss"].get("lambda_sn", 1.0))
            L_block = block_loss(Mb, Mb_gt) * float(cfg["loss"].get("lambda_b", 1.0))
            L_bce = (weighted_mask_bce(Ms, Ms_gt, args.mask_bce_negative_weight)
                     + weighted_mask_bce(Mb, Mb_gt, args.mask_bce_negative_weight)) * args.mask_bce_weight
            loss_g = L_sn + L_block + L_bce
            loss_d = loss_g.detach() * 0
            parts = [
                loss_g.detach() * 0,
                loss_g.detach() * 0,
                loss_g.detach() * 0,
                loss_g.detach() * 0,
                L_sn,
                L_block,
                loss_g.detach() * 0,
                loss_g.detach() * 0,
                loss_g.detach() * 0,
                L_bce,
            ]
        else:
            opt_d.zero_grad(set_to_none=True)
            with torch.no_grad():
                Icomp = G(Iin)[-1]
            real_g, real_l = D(Igt, Mb_gt)
            fake_g, fake_l = D(Icomp, Mb_gt)
            loss_d = (EnsExamLoss.hinge_loss_D(real_g, fake_g) + EnsExamLoss.hinge_loss_D(real_l, fake_l)) / 2
            loss_d.backward()
            opt_d.step()

            gen_out = G(Iin)
            fake_g, fake_l = D(gen_out[-1], Mb_gt)
            loss_g, parts = criterion(gen_out, gt, (fake_g, fake_l))
            parts = [*parts, loss_g.detach() * 0]
        loss_g.backward()
        opt_g.step()

        if not torch.isfinite(loss_g).item() or not torch.isfinite(loss_d).item():
            save_checkpoint(output_dir / f"micro_region_probe_step{step:04d}_nonfinite.pth", step)
            raise RuntimeError(f"non-finite loss at step {step}")

        row = [
            step,
            f"{float(loss_g.detach().cpu()):.6f}",
            f"{float(loss_d.detach().cpu()):.6f}",
            *[f"{float(part.detach().cpu()):.6f}" for part in parts],
        ]
        with history_path.open("a", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(row)

        if step == 1 or step % args.log_every == 0 or step == args.max_steps:
            elapsed = time.time() - start
            print(
                f"step={step}/{args.max_steps} "
                f"G={row[1]} D={row[2]} lr_part={row[4]} "
                f"sn={row[7]} block={row[8]} "
                f"preserve={row[9]} mb_leak={row[10]} box_preserve={row[11]} "
                f"bce={row[12]} "
                f"elapsed={elapsed:.1f}s",
                flush=True,
            )

        if args.save_every > 0 and (step % args.save_every == 0 or step == args.max_steps):
            save_checkpoint(output_dir / f"micro_region_probe_step{step:04d}.pth", step)

        del Iin, Ms_gt, Mb_gt, Box_preserve_gt, Igt4, Igt2, Igt1, Igt, gt
        if not args.mask_only:
            del gen_out, fake_g, fake_l
        else:
            del Ms, Mb
        del loss_g, loss_d, parts
        gc.collect()
        if device.type == "mps":
            torch.mps.empty_cache()

    save_checkpoint(output_dir / "micro_region_probe.pth", args.max_steps)
    print(f"saved={output_dir / 'micro_region_probe.pth'}", flush=True)


if __name__ == "__main__":
    main()
